### ISSUE TITLE
Inventory view not displaying Category, Vendor, or Manufacturer

### ISSUE THREAD

**Issue by steve011** [cphazen/Inventory-System#16]
For some reason the inventory view is not displaying Category, Vendor, or Manufacturer. It's shows N\A for all the values, at least on my end anyways.

**Comment by jacobbrown72** [comment]
I made some changes in the json file and the script.  I would first try
droping the database in mongoose, then try running grunt to re-initialize
the database.

**Comment by steve011** [comment]
Thanks, yeah I figured it out.

**Comment by jacobbrown72** [comment]
Hey, I saw all of your changes and have them running on my system.
Everything looks good so far.  Is there anything you would like me to work
on?

Have we added the view to create a part with a serial number and firmware?

**Comment by steve011** [comment]
No, I'm not sure how you want to go about adding that. So if you can figure it out, that would be awesome.

**Comment by jacobbrown72** [comment]
Ok, I'll start working on that.  Before I get started on that though, I
will work on organizing the table by category.

**Comment by cphazen** [comment]
I can create that view but I need to know which partTypes need to use them.

**Comment by jacobbrown72** [comment]
I think I answered that question, but in a different email
